### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'setKeyExportFlag')

### ISSUE THREAD

**Issue by fmorency** [Web3Auth/web3auth-web#2036]
### **Describe the bug**

I'm trying to update the cosmos-kit [1] Web3Auth wallet [2] from v7 to v9.4.5 and I'm getting the following error

```
utils.js:127 Error initializing Web3Auth client: TypeError: Cannot read properties of undefined (reading 'setKeyExportFlag')
    at eval (noModal.js:124:47)
    at Array.map (<anonymous>)
    at Web3AuthNoModal.init (noModal.js:72:59)
    at async connectClientAndProvider (utils.js:124:1)
    at async Web3AuthClient.ensureSetup (client.js:35:36)
    at async Web3AuthClient.connect (client.js:102:1)
    at async Web3AuthChainWallet.update (chain-wallet.js:118:1)
    at async Web3AuthChainWallet.connect (wallet.js:179:1)
```

Everything works fine when updating from v7 to v8.12.4.

I followed the migration guides from the Web3Auth documentation.

[1]: https://github.com/cosmology-tech/cosmos-kit
[2]: https://github.com/cosmology-tech/cosmos-kit/tree/main/wallets/web3auth

### **Device Info (please complete the following information):**

- Device: PC
- OS: Linux
- Browser Chromium
- Version 131.0.6778.108 (Official Build) Arch Linux (64-bit)
- Web3Auth Version 9.4.5

### **Additional context**

I tried disabling the Export Key feature from our paid account but got the error still.

Again, everything works fine when updating from v7 to v8.12.4.

Is this a Web3Auth issue?

**Comment by yashovardhan** [comment]
Hey @fmorency 

Can you please add your code snippets here as well for our review?

**Comment by tli-test** [comment]
Hi @yashovardhan,

You can use the `bump-web3auth-9` branch at https://github.com/fmorency/cosmos-kit/tree/bump-web3auth-9

The Web3Auth-related code is located in `wallets/web3auth`: https://github.com/fmorency/cosmos-kit/tree/bump-web3auth-9/wallets/web3auth

**Comment by yashovardhan** [comment]
hey @fmorency 

Can you please pass the `privateKeyProvider` in your `Web3AuthNoModal` constructor, instead of `AuthAdapter`?

**Comment by fmorency** [comment]
> hey @fmorency
> 
> Can you please pass the `privateKeyProvider` in your `Web3AuthNoModal` constructor, instead of `AuthAdapter`?

It worked! Thank you!
